
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database.types';

const SUPABASE_URL = "https://pmhdeeiazpelwjwsikud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtaGRlZWlhenBlbHdqd3Npa3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjgyOTgsImV4cCI6MjA2MDU0NDI5OH0.5KDlAiFRqXd0BX1vV1JhtdQqBk_6Yr06hRjc9OMXuKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
